# Generated by Django 5.2.8 on 2026-01-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='curso',
            new_name='cursos',
        ),
    ]
