# Generated by Django 5.2.8 on 2026-02-04 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_rename_curso_cursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('dni', models.PositiveBigIntegerField(verbose_name='Documento')),
                ('sexo', models.CharField(choices=[('F', 'femenino'), ('M', 'masculino'), ('O', 'otro')], default='O', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='cursos',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.docente'),
        ),
    ]
