# Generated by Django 5.2.8 on 2026-02-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_docente_cursos_docente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docente',
            options={'ordering': ['apellido', '-nombre'], 'verbose_name': 'docente', 'verbose_name_plural': 'docentes'},
        ),
        migrations.AlterModelTable(
            name='docente',
            table='Docente',
        ),
    ]
