# Generated by Django 5.2.8 on 2026-02-13 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_alter_docente_options_alter_docente_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.docente'),
        ),
    ]
